language: cpp

compiler:
  - gcc
  - clang

before_install:   # Install g++ 4.8 for c++11 features.
  - sudo apt-get install -qq python-software-properties
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq libboost-all-dev

  # Install eigen 3.2.4 from source, because the apt-get's eigen version (3.0.X) is too old.
  - hg clone -u 3.2.4 https://bitbucket.org/eigen/eigen/ eigen-source
  - mkdir eigen-build
  - cd eigen-build
  - cmake ../eigen-source
  - sudo make install
  - cd ..

before_script:
  - mkdir cmake-build
  - cd cmake-build
  - cmake ..

script:
  - make -j
  - make test
  - sudo make install
